version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    command: ["bun", "run", "dev", "--", "--host"]

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
