#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run the version update script before the build
node ./update-version.js

# Run your build process (as you already do)
bun run build

# Continue with the commit